### ISSUE TITLE
Get access to other tabs

### ISSUE THREAD

**Issue by letos07** [slimjack/IWC-SignalR#7]
Hey!

Please help me, I am using you code for SignalR application. It resolve the problem with multiple tabs, but If event was fired I see it in all tabs. How I can get access to others tab without connection id? I need can show data only if that tab that I wont.

**Comment by slimjack** [comment]
You think that propagation of events to all tabs is wrong? Why? By design clients work with _IWC-SignalR_ like with usual _SignalR_. So, events should be raised even if this is not a connection owner.

To communicate between tabs you can use `EventBus` or `SharedData`. To distinguish tabs you can use `windowId`s from `WindowMonitor`.

**Comment by letos07** [comment]
Its doesnt wrong, but I need to show notification only in that browser tab from that I send my request to server.

**Comment by slimjack** [comment]
You can mark message with windowId (server in this case should respond with this windowId too) and then filter messages by windowId.

**Comment by letos07** [comment]
ok, thanks. Only one question: how I can get signalR connectionId from other tabs?
SJ.iwc.SignalR.getConnectionOwnerWindowId() - return only windowId, not connection? maybe you store this value?
